cask_args appdir: '/Applications'

brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'openssl'
brew 'node'
brew 'rbenv'
brew 'wget'
brew 'source-highlight' # Used for syntax highlighting in 'less'

cask 'atom'
cask 'firefox'
cask 'google-chrome'
cask 'transmission'
cask 'vlc'
